// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mmdp.proto

package io.guanghuizeng.mmdp.protocol;

public final class MmdpProtos {
  private MmdpProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.guanghuizeng.mmdp.protocol.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
     *
     * <pre>
     * function 
     * </pre>
     */
    boolean hasFunction();
    /**
     * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
     *
     * <pre>
     * function 
     * </pre>
     */
    io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function getFunction();

    /**
     * <code>optional string source = 2 [default = ""];</code>
     *
     * <pre>
     * data 
     * </pre>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 2 [default = ""];</code>
     *
     * <pre>
     * data 
     * </pre>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 2 [default = ""];</code>
     *
     * <pre>
     * data 
     * </pre>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>optional string target = 3 [default = ""];</code>
     */
    boolean hasTarget();
    /**
     * <code>optional string target = 3 [default = ""];</code>
     */
    java.lang.String getTarget();
    /**
     * <code>optional string target = 3 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <code>optional string data = 4 [default = ""];</code>
     */
    boolean hasData();
    /**
     * <code>optional string data = 4 [default = ""];</code>
     */
    java.lang.String getData();
    /**
     * <code>optional string data = 4 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>optional int32 result = 7 [default = 0];</code>
     *
     * <pre>
     * result 
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional int32 result = 7 [default = 0];</code>
     *
     * <pre>
     * result 
     * </pre>
     */
    int getResult();

    /**
     * <code>optional string info = 8 [default = ""];</code>
     *
     * <pre>
     * info 
     * </pre>
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 8 [default = ""];</code>
     *
     * <pre>
     * info 
     * </pre>
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 8 [default = ""];</code>
     *
     * <pre>
     * info 
     * </pre>
     */
    com.google.protobuf.ByteString
        getInfoBytes();
  }
  /**
   * Protobuf type {@code io.guanghuizeng.mmdp.protocol.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.guanghuizeng.mmdp.protocol.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function value = io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                function_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              source_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              target_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              data_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              result_ = input.readInt32();
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              info_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.guanghuizeng.mmdp.protocol.MmdpProtos.internal_static_io_guanghuizeng_mmdp_protocol_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.guanghuizeng.mmdp.protocol.MmdpProtos.internal_static_io_guanghuizeng_mmdp_protocol_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.class, io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code io.guanghuizeng.mmdp.protocol.Message.Function}
     */
    public enum Function
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ECHO = 0;</code>
       */
      ECHO(0, 0),
      /**
       * <code>SAVE = 1;</code>
       */
      SAVE(1, 1),
      /**
       * <code>SORT = 2;</code>
       */
      SORT(2, 2),
      /**
       * <code>WRITE = 3;</code>
       */
      WRITE(3, 3),
      /**
       * <code>MAX = 4;</code>
       */
      MAX(4, 4),
      ;

      /**
       * <code>ECHO = 0;</code>
       */
      public static final int ECHO_VALUE = 0;
      /**
       * <code>SAVE = 1;</code>
       */
      public static final int SAVE_VALUE = 1;
      /**
       * <code>SORT = 2;</code>
       */
      public static final int SORT_VALUE = 2;
      /**
       * <code>WRITE = 3;</code>
       */
      public static final int WRITE_VALUE = 3;
      /**
       * <code>MAX = 4;</code>
       */
      public static final int MAX_VALUE = 4;


      public final int getNumber() { return value; }

      public static Function valueOf(int value) {
        switch (value) {
          case 0: return ECHO;
          case 1: return SAVE;
          case 2: return SORT;
          case 3: return WRITE;
          case 4: return MAX;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Function>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Function>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Function>() {
              public Function findValueByNumber(int number) {
                return Function.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final Function[] VALUES = values();

      public static Function valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Function(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:io.guanghuizeng.mmdp.protocol.Message.Function)
    }

    private int bitField0_;
    public static final int FUNCTION_FIELD_NUMBER = 1;
    private io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function function_;
    /**
     * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
     *
     * <pre>
     * function 
     * </pre>
     */
    public boolean hasFunction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
     *
     * <pre>
     * function 
     * </pre>
     */
    public io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function getFunction() {
      return function_;
    }

    public static final int SOURCE_FIELD_NUMBER = 2;
    private java.lang.Object source_;
    /**
     * <code>optional string source = 2 [default = ""];</code>
     *
     * <pre>
     * data 
     * </pre>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string source = 2 [default = ""];</code>
     *
     * <pre>
     * data 
     * </pre>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 2 [default = ""];</code>
     *
     * <pre>
     * data 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_FIELD_NUMBER = 3;
    private java.lang.Object target_;
    /**
     * <code>optional string target = 3 [default = ""];</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string target = 3 [default = ""];</code>
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string target = 3 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private java.lang.Object data_;
    /**
     * <code>optional string data = 4 [default = ""];</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string data = 4 [default = ""];</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string data = 4 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 7;
    private int result_;
    /**
     * <code>optional int32 result = 7 [default = 0];</code>
     *
     * <pre>
     * result 
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 result = 7 [default = 0];</code>
     *
     * <pre>
     * result 
     * </pre>
     */
    public int getResult() {
      return result_;
    }

    public static final int INFO_FIELD_NUMBER = 8;
    private java.lang.Object info_;
    /**
     * <code>optional string info = 8 [default = ""];</code>
     *
     * <pre>
     * info 
     * </pre>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string info = 8 [default = ""];</code>
     *
     * <pre>
     * info 
     * </pre>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string info = 8 [default = ""];</code>
     *
     * <pre>
     * info 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      function_ = io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function.ECHO;
      source_ = "";
      target_ = "";
      data_ = "";
      result_ = 0;
      info_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFunction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, function_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSourceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTargetBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(7, result_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(8, getInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, function_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSourceBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTargetBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDataBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, result_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(io.guanghuizeng.mmdp.protocol.MmdpProtos.Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.guanghuizeng.mmdp.protocol.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.guanghuizeng.mmdp.protocol.Message)
        io.guanghuizeng.mmdp.protocol.MmdpProtos.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.guanghuizeng.mmdp.protocol.MmdpProtos.internal_static_io_guanghuizeng_mmdp_protocol_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.guanghuizeng.mmdp.protocol.MmdpProtos.internal_static_io_guanghuizeng_mmdp_protocol_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.class, io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Builder.class);
      }

      // Construct using io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        function_ = io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function.ECHO;
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.guanghuizeng.mmdp.protocol.MmdpProtos.internal_static_io_guanghuizeng_mmdp_protocol_Message_descriptor;
      }

      public io.guanghuizeng.mmdp.protocol.MmdpProtos.Message getDefaultInstanceForType() {
        return io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.getDefaultInstance();
      }

      public io.guanghuizeng.mmdp.protocol.MmdpProtos.Message build() {
        io.guanghuizeng.mmdp.protocol.MmdpProtos.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.guanghuizeng.mmdp.protocol.MmdpProtos.Message buildPartial() {
        io.guanghuizeng.mmdp.protocol.MmdpProtos.Message result = new io.guanghuizeng.mmdp.protocol.MmdpProtos.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.function_ = function_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.info_ = info_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.guanghuizeng.mmdp.protocol.MmdpProtos.Message) {
          return mergeFrom((io.guanghuizeng.mmdp.protocol.MmdpProtos.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.guanghuizeng.mmdp.protocol.MmdpProtos.Message other) {
        if (other == io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.getDefaultInstance()) return this;
        if (other.hasFunction()) {
          setFunction(other.getFunction());
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000002;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasTarget()) {
          bitField0_ |= 0x00000004;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000008;
          data_ = other.data_;
          onChanged();
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000020;
          info_ = other.info_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFunction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.guanghuizeng.mmdp.protocol.MmdpProtos.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.guanghuizeng.mmdp.protocol.MmdpProtos.Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function function_ = io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function.ECHO;
      /**
       * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
       *
       * <pre>
       * function 
       * </pre>
       */
      public boolean hasFunction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
       *
       * <pre>
       * function 
       * </pre>
       */
      public io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function getFunction() {
        return function_;
      }
      /**
       * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
       *
       * <pre>
       * function 
       * </pre>
       */
      public Builder setFunction(io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        function_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .io.guanghuizeng.mmdp.protocol.Message.Function function = 1;</code>
       *
       * <pre>
       * function 
       * </pre>
       */
      public Builder clearFunction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        function_ = io.guanghuizeng.mmdp.protocol.MmdpProtos.Message.Function.ECHO;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 2 [default = ""];</code>
       *
       * <pre>
       * data 
       * </pre>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       *
       * <pre>
       * data 
       * </pre>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       *
       * <pre>
       * data 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       *
       * <pre>
       * data 
       * </pre>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       *
       * <pre>
       * data 
       * </pre>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2 [default = ""];</code>
       *
       * <pre>
       * data 
       * </pre>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object target_ = "";
      /**
       * <code>optional string target = 3 [default = ""];</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string target = 3 [default = ""];</code>
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string target = 3 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string target = 3 [default = ""];</code>
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string target = 3 [default = ""];</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000004);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>optional string target = 3 [default = ""];</code>
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>optional string data = 4 [default = ""];</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string data = 4 [default = ""];</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            data_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string data = 4 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string data = 4 [default = ""];</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4 [default = ""];</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>optional string data = 4 [default = ""];</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>optional int32 result = 7 [default = 0];</code>
       *
       * <pre>
       * result 
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 result = 7 [default = 0];</code>
       *
       * <pre>
       * result 
       * </pre>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>optional int32 result = 7 [default = 0];</code>
       *
       * <pre>
       * result 
       * </pre>
       */
      public Builder setResult(int value) {
        bitField0_ |= 0x00000010;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 result = 7 [default = 0];</code>
       *
       * <pre>
       * result 
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000010);
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 8 [default = ""];</code>
       *
       * <pre>
       * info 
       * </pre>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string info = 8 [default = ""];</code>
       *
       * <pre>
       * info 
       * </pre>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            info_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 8 [default = ""];</code>
       *
       * <pre>
       * info 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 8 [default = ""];</code>
       *
       * <pre>
       * info 
       * </pre>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 8 [default = ""];</code>
       *
       * <pre>
       * info 
       * </pre>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 8 [default = ""];</code>
       *
       * <pre>
       * info 
       * </pre>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        info_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.guanghuizeng.mmdp.protocol.Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:io.guanghuizeng.mmdp.protocol.Message)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_guanghuizeng_mmdp_protocol_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_guanghuizeng_mmdp_protocol_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmmdp.proto\022\035io.guanghuizeng.mmdp.proto" +
      "col\"\341\001\n\007Message\022A\n\010function\030\001 \002(\0162/.io.g" +
      "uanghuizeng.mmdp.protocol.Message.Functi" +
      "on\022\020\n\006source\030\002 \001(\t:\000\022\020\n\006target\030\003 \001(\t:\000\022\016" +
      "\n\004data\030\004 \001(\t:\000\022\021\n\006result\030\007 \001(\005:\0010\022\016\n\004inf" +
      "o\030\010 \001(\t:\000\"<\n\010Function\022\010\n\004ECHO\020\000\022\010\n\004SAVE\020" +
      "\001\022\010\n\004SORT\020\002\022\t\n\005WRITE\020\003\022\007\n\003MAX\020\004B+\n\035io.gu" +
      "anghuizeng.mmdp.protocolB\nMmdpProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_io_guanghuizeng_mmdp_protocol_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_guanghuizeng_mmdp_protocol_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_guanghuizeng_mmdp_protocol_Message_descriptor,
        new java.lang.String[] { "Function", "Source", "Target", "Data", "Result", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
